site_name: NL-BIOMERO Documentation
site_url: https://nl-bioimaging.github.io/NL-BIOMERO/
site_author: Core Facility Cellular Imaging
copyright: 2025, Core Facility Cellular Imaging

docs_dir: docs

nav:
  - Home: index.md
  - System Administration:
      - Overview: sysadmin/index.md
      - Deployment: sysadmin/deployment.md
      - Backup & Restore: sysadmin/backup-restore.md
      - Docker Compose Scenarios: sysadmin/docker-compose-scenarios.md
      - Linux Deployment: sysadmin/linux-deployment.md
      - OMERO-BIOMERO Admin: sysadmin/omero-biomero-admin.md
      - SLURM Integration: sysadmin/slurm-integration.md
      - Development Setup: sysadmin/development-setup.md
  - Developer Guide:
      - Overview: developer/index.md
      - Getting Started: developer/getting-started.md
      - Architecture: developer/architecture.md
      - Containers:
          - Overview: developer/containers/index.md
          - Biomero Importer: developer/containers/biomero-importer.md
          - Biomero Worker: developer/containers/biomeroworker.md
          - Database: developer/containers/database.md
          - Metabase: developer/containers/metabase.md
          - OMERO Server: developer/containers/omeroserver.md
          - OMERO Web: developer/containers/omeroweb.md
          - Releases: developer/containers/releases.md
      
  - User Guide:
      - Overview: user/index.md
      - Getting Started: user/getting-started.md
      # Add more user docs as needed

# Theme and plugins
theme:
  name: material
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
plugins:
  - search
  - include-markdown
